CREATE DATABASE IF NOT EXISTS tonsOfTacos;

USE tonsOfTacos;

DROP TABLE IF EXISTS order_item;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS menu_item;

DROP TABLE IF EXISTS customer;


CREATE TABLE customer(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(40) NOT NULL,
name VARCHAR(40) NOT NULL,
phone_number VARCHAR(12) NOT NULL
);

CREATE TABLE menu_item(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
category VARCHAR(30) NOT NUll,
description VARCHAR(255) NOT NUll,
item_name VARCHAR(30) NOT NUll,
item_size VARCHAR(100) DEFAULT NULL,
img_url VARCHAR(255) NOT NUll,
unit_price DECIMAL(19, 2) NOT NUll
);


CREATE TABLE orders(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
customer_id BIGINT NOT NULL,
order_total DECIMAL(19, 2) NOT NULL,
order_uuid VARCHAR(255) NOT NULL,
CONSTRAINT FK_customer_id FOREIGN KEY (customer_id) REFERENCES customer(id)
);


CREATE TABLE order_item(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
menu_item_id BIGINT NOT NULL,
order_id BIGINT NOT NULL, 
quantity INT(2) NOT NULL,
total DECIMAL(19, 2)NOT NULL,
CONSTRAINT FK_menu_item_id FOREIGN KEY (menu_item_id) REFERENCES menu_item(id),
CONSTRAINT FK_order_id FOREIGN KEY (order_id) REFERENCES orders(id)
);




